--- 
wordpress_id: 24
title: It's not... <i>gay</i>...
wordpress_url: http://blog.6thdensity.net/?p=24
layout: post
---
<p>For guys who want to be well balanced and normal without being a sitcom characture, exit <u>Queer Eye...</u>, and enter <a href="http://seattlepi.nwsource.com/lifestyle/219642_mandates.html">the man date</a> (my male friends are already uncomfortable):</p><blockquote>Simply defined, a man date is two heterosexual men socializing without the crutch of business or sports. It is two guys meeting for the kind of outing a straight man might reasonably arrange with a woman. Dining together across a table without the aid of a television is a man date; eating at a bar is not. Taking a walk in the park together is a man date; going for a jog is not. Attending the movie "Friday Night Lights" is a man date, but going to see the Jets play is definitely not.</blockquote><p>Now, I'll be up front - I have definately done these before, and I'm fine with them.  But never, <i>ever</i> without the obligatory and self-depreciating gay jokes.</p><blockquote>"If men become too close to other men, then they are always vulnerable to this accusation of, 'Oh, you must be gay,' " said Gregory Lehne, a medical psychologist at the Johns Hopkins School of Medicine who has studied gender issues. At the same time, he added, "When you have women in the same world and seeking equality with men, then all of a sudden issues emerge in the need to maintain the male sex role."

And thus a simple meal turns into social Stratego. Some men avoid dinner altogether unless the friend is coming from out of town or has a specific problem that he wants advice about. Otherwise, grabbing beers at a bar will do just fine, thank you.</blockquote><p>Does that resonate, fellow males?  Does here.  I can definately do these dates, and I'm not <i>really</i> concerned about my reputation, but it still bothers me (and my buds) enough to joke about it incessantly nonetheless.  It even bothers our significant others enough (perhaps more) to give us a hard time about it.</p><p>Perfect example of this is my friend, Bill.  We've been going to <a href="http://www.brotherspast.com">BP shows</a> for years, which technically could be considered a man date.  And we've also met for dinner (though a bar has usually been involved - at least somewhat).  But his girlfriend and my fiance - who are best friends - kid us more about being gay than we kid each other.  I find the idea that they would be even subconsciously threatened by our man dates absurd beyond belief - but could there be some truth to it?  Or maybe this is just them being faithful members of their gender and playing sex politics against our male identities - who knows.</p><p>But the most interesting thing to me about all this is the concern that we men may be missing something.  I know my arrangement to meet with my best man <a href="http://mattwalters.net">Matt</a> meant more to me than he probably knows, and helped me at a very critical juncture in my recent life.  How often do we avoid this kind of interaction, though, to our obvious disadvantage?<blockquote>Jim O'Donnell, a professor of business and economics at Huntington University in Indiana, who said his life had been changed by a male friend, urges men to get over their discomfort in socializing one on one because they have much to gain from the emotional support of male friendships. (Women understand this instinctively, which is why there is no female equivalent to the awkward man date; straight women have long met for dinner or a movie without a second thought.)

"A lot of quality time is lost as we fritter around with minor stuff like the Final Four scores," said O'Donnell, who was on the verge of divorce in the mid-1980s before a series of conversations over meals and walks with a friend 20 years his senior changed his thinking. "He was instrumental in turning me around in the vulnerability that he showed," said O'Donnell, who wrote about the friendship in a book, "Walking With Arthur." "I can remember times when he wanted to know why I was going to leave my wife. No guy had ever done that before."

...

Dinner with a friend has not always been so fraught. <b>Before women were considered men's equals, some gender historians say, men routinely confided in and sought advice from one another in ways they did not do with women, even their wives.</b> Then, these scholars say, two things changed during the past century: an increased public awareness of homosexuality created a stigma around male intimacy, and at the same time women began encroaching on traditionally male spheres, causing men to become more defensive about notions of masculinity.</blockquote></p><p>It makes you wonder whether all the gay jokes us guys crack hurt more people than just gays...</p><p>Hattip to <a href="http://macstansbury.com">Mac</a>.</p>
