--- 
wordpress_id: 540
title: "Understanding the Neoconservative Gestalt: The Primacy of Opinion"
wordpress_url: http://blog.6thdensity.net/?p=540
layout: post
---
<p>I've encountered my share of right wing blowhards, but Christopher Hitchens demonstrates just how little regard neoconservatives hold for thoughtful discourse and debate (lynchpins of any democratic republic).  Via <a href="http://majikthise.typepad.com">majikthise</a>, <a href="http://ezraklein.typepad.com/blog/2006/10/christopher_hit.html">Ezra Klein relates an incident</a> involving Hitchens at a dinner party:</p>
<blockquote><p>Hitchens then recalls a time when Dean spoke against mandatory parental notification laws by telling of 12-year-old child who'd come to his office seeking an abortion. The baby was her father's. But Dean hadn't told the authorities of the incident, and it seemed that it may have happened to someone else, or been exaggerated, or something. Hitchens uses this to brand Dean a "pathological liar," and when some at the table protest, Hitchens turns his shotgun full of crazy on the assembled:</p>
<blockquote><p>"Fine, now that I know that, to you, medical ethics are nothing, you've told me all I need to know. I'm not trying to persuade you. Do you think I care whether you agree with me? No. I'm telling you why I disagree with you. That I <em>do</em> care about. I have no further interest in any of your opinions. There's nothing you wouldn't make an excuse for. You know what? I wouldn't want you on my side. I was telling you why I knew that Howard Dean was a psycho and a fraud , and you say 'That's O.K.' Fuck off. No, I mean it: fuck off. I'm telling you what I think are standards and you say, 'What standards? It's fine, he's against the Iraq War.' Fuck. Off. You're MoveOn.org. Any liar will do. He's anti-Bush. Fuck off...Save it sweetie, for someone who cares. It will not be me. You love it, you suck on it. I now know what your standards are, and now you know what mine are, and that's all the difference -- I hope -- in the world."</p></blockquote>
</blockquote>
<p>This is pretty harsh, but I'm interested in the lack of interest in persuasion.  This lack of faith in the process of judicious and deliberate conversation explains pretty well why neocons feel no need to have facts support their positions - it's not even incumbent on them to convince us of anything!  The important thing is that they know what they believe, and they're in power - so suck on it.</p>
<p>I'm sure the above point doesn't come as news to most readers.  What floored me, however, is how similar this is to something that <a href="http://rhog.blogspot.com">Andy Stevenson</a> said to me on RTG's blog a few years back (unfortunately RTG blew up the archives from that period).  Since I can't find the records of the dialogue, I can only paraphrase it as I remember it: I was pointing out flaws in his argument - not promoting mine - and he basically said he didn't care what I believed, he had no interest in persuading me or defending his argument whatsoever, and that what mattered was convincing other people so that his party could be in power.  He believes it, and if I don't like it, tough titties.  And his dad can beat up my dad.</p>
<p>What neocons are afraid of more than anything else is having to defend their positions rationally.  Rational debate means that they have to rely on facts and consistency and play down appeals to emotion.  So they avoid it at all costs.  You see it on Fox News.  You see it in the wild rants of Rush Limbaugh.  You definitely see it in the way Bush administration officials toss around the terms "ties" and "links" and "WMD" as if the words are simply policy tools disconnected from things like reality and one's sacred reputation.</p>
<p>And believe me, as a radical thinker, I understand about fundamental ideological principles and irreconcilable differences.  But you engage in debate still in order to challenge your own beliefs and positions as well as strengthen them.  Neocons are afraid of the logical conclusions their arguments imply, and above all else they stay away from self-examination.  Above all, when you find that perhaps you cannot agree as a result of axiomatic differences, you acknowledge and respect that - instead of simply dismissing the other as unworthy of convincing in the first place.</p><p>And Andy was one of the brighter ones... that's what gets me.  He's a very strong and clever writer, and yet <em>even he </em>resorted to such an anti-intellectual, pithy defense.  <a href="http://blog.6thdensity.net/?p=536">As I said earlier</a>, the right wing is always interested in winning the debate of ideas on a technicality, not on merit.
</p>
