--- 
wordpress_id: 465
title: The Utility of Hipocrisy
wordpress_url: http://blog.6thdensity.net/?p=465
layout: post
---
<p>To her credit, RTG makes <a title="RTG: Beyond Hipocrisy" href="http://rightthinkinggirl.com/2006/07/05/beyond-hypocrisy/">a great case</a> for going easier on people who make mistakes in their personal lives:</p>
<blockquote>
<p>What really bothers me is the fact that hypocrisy has become the primary device to discredit the other side.  When Rush Limbaugh admitted on the air that he was battling drug addiction, Liberals nearly fainted with pleasure.  It was a great a-ha moment but it was lacking in real substance - just like Pelosi’s relationship with unions.   Rush’s problem with prescribed medication for back pain was, in my view, different than a heroin addict knocking over a Stop N Go for cash, and in any case - his drug addiction doesn’t make his views wrong or illegal or in any way suspect.  It was character assasination.</p>
</blockquote>
<p>It makes me hope that, finally, RTG is getting it: humans are fallable, they make mistakes, and we should have compassion for them instead of expecting them to conform to some social straightjacket at gunpoint.</p>
<blockquote>
<p>The point, I think, is to continue to strive for perfection.   If you fail - and you might - then your moral authority might be compromised but <strong>there is more to life than moral authority</strong>.  There is objective Right and Wrong.</p>
</blockquote>
<p>Exactly: there IS more to life than moral authority.  Why that is has nothing to do with whether morality is objective or subjective, though.  Rather it has to do with the nature of authority itself: it, too, is human, subject to the same indiscretions, mistakes, and personal failing that it seeks out in others.</p>
<p>But people like RTG and Rush Limbaugh can't give up on the myth.  In order for people to act in the way they believe is objectively right and moral, they need a State that is poking into people's personal lives, making sure they're not committing offenses towards God or whatever this moral authority actually is.  And so, people like Rush - who are suffering - get dragged through the system.  It's not so much hipocritical as tragic when people continue to worship an "authority" even as it's bludgeoning them.  Like battered housewives, moral absolutists keep returning to the abuser, subjecting the entire society to more violence and suffering in the name of "objective right".</p>
<p>If the Right was consistent in being compassionate towards ALL for their indiscretions - even those "objectively wrong", that would be one thing.  But many of the vices conservatives try to tackle they do with "zero tolerance" mentalities, criminalizing the population you claim to now want to be kinder and gentler towards.  That's what happens when you break into people's personal lives to tell them what to do - no wonder it happens to right wing blowhards just like the rest of us.</p>
<p>The problem is precisely the one I set out in <a title="Human Nature: the Fulcrum of Political Polarity" href="http://www.wrongthinkinggirl.com/2006/07/02/human-nature-the-fulcrum-of-political-polarity/">another essay</a>: conservatives' absolute demands on human perfection are fine <span style="font-style: italic">except</span> that they want to use the state to realize them.  While God may have absolute knowledge of who's deserving of compassion and who deserves the book thrown at a person, the State or Rush or RTG have very little ability to make objective judgments where the level of harm is not demonstrable - even when starting from an objective morality.</p>
<p>This is why victimless crimes are so wrong: because they rely on fallable bureaucrats to enforce, instead of actually resonding to injured parties.  There is no compaint to which the State can respond, because there is nobody that is really hurt in any legally consistent sense.  So the government has to seek out the "crimes", and yes, they often expose secrets (though more often they aren't those of the well connected like Rush, but rather average joes who don't have a big soapbox).  How ironic: the very problems RTG has with hipocrisy arise from the hipocrisy inherent in vice laws.  Vice laws short circuit the entire mechanism of traditional Anglo-American common law in order to penalize us for activities that, at most, are hurting only ourselves.</p>
<p>Finally, <a title="Comments on RTG" href="http://rightthinkinggirl.com/2006/07/05/beyond-hypocrisy/#comment-5148">one commenter</a> on RTG.com tries to advance the argument that the hipocrisy of the Right is somehow better than the Left because it doesn't impose the large social costs that the Left does.  Of course, this is patently false.  The U.S. has the largest prison population of any country in the world, and over half of our prisoners are victims of the drug war policies Rush has taken pains to endorse.  In this area alone <a title="Drug War Facts: Economics" href="http://www.drugwarfacts.org/economi.htm">the social costs of prohibition are far too large to be ignored</a>.</p>
<p>But, as I set out in <a title="Social Memory Complex: Limited Liability and Market Calculation" href="http://blog.6thdensity.net/?p=458">a post</a> on my blog, conservatives have a tendency to ignore costs they find undesirable to factor into the balance sheet of "progress".  These costs don't disappear - they're simply offloaded to an innocent third party (see inner cities for copious examples).  In the case of the War on Drugs, as in other cases of state intervention, it is usually left to the socially conscious in society - typically, the bleeding heart types - to identify and speak up about the intangible effects of these policies.  However, the only reason they are so hard to recognize is because the damage was never factored into the original policy decisions - making conservatives at least as irresponsible and socially freeloading as liberals.  Hipocrisy is all about framing the debate to ignore the full, honest picture - and in conservative politics we cannot ignore its obvious utility in moving forward a moral agenda.</p>
