--- 
wordpress_id: 515
title: More Thoughts on Conspiracy
wordpress_url: http://blog.6thdensity.net/?p=515
layout: post
---
My <a title="Two Views on Conspiracy and Complexity" href="http://blog.6thdensity.net/?p=507">recent post</a> on conspiracies did not really solve anything for me, nor did it crystalize a complete thesis like I expected.  Complexity is an important element to deal with, but there's more to be said.  It did, however, give me a starting point from which to express further opinions on the concept of conspiracy and the theories surrounding it.  I think there's much more to be said above and beyond merely reacting to the wave of Hallmark 9/11 nostalgia that yesterday's blogosphere offered up.

As I stated in my previous post, I'm interested in conspiracy as a function of collective social dynamics.  <a title="Why the 9/11 Conspiracy Theories Won't Go Away" href="http://www.time.com/time/magazine/article/0,9171,1531304,00.html">The Time article I quoted</a> made a point about the psychological need to explain complexity through conspiracy.  Unlike the popular thinking on the matter, however, I don't think the existence of theories makes conspiracy any more or less likely.  There are theories about every imaginable dynamic we've been able to identify in the universe, from theology to physics to sociology and politics.  All of them represent best guesses, some more or less supported by fact, regardless of their level of acceptance.

The problem is not theoretical speculation nor the uncertainty that such theories aim to alleviate (unless, I suppose, you're a politician).  It is the capacity for society itself to establish the legitimacy and transparency of the political order in which it exists. Now, the basic dynamics of this should not be difficult to understand, though I'm not suggesting that running the world is a simple task.  Some dimensions of life are naturally opaque - the human soul, quantum physics, etc.  I'm not entirely certain that politics is one of those areas.  People deal with interpersonal politics on a more or less daily basis - in the workplace, in the family, in their social circles.

<!--more-->Surely there are few areas where speculative extrapolation from personal experience is more apt than politics.  Is there any real, substantive difference between your approach to Bush and your estimation of your boss or principal?  Isn't there some commonalities in the politics of the bureaucrats with whom he surrounds himself and the ones with whom you've had to deal?  There may be factual gaps concerning 9/11, but an intelligent person can draw his own conclusions about the surrounding politics without too much expert assistance.

The political context is more important than most people realize.  If nothing else, 9/11 demonstrates how vital an understanding of the world we live in is.  Yet if this understanding can only come from politically palatable sources, how do we view the official power structure in an even-handed manner?  How can we assure ourselves that those who exercise massive power on our behalf are actually on the level with us - whether or not we can anticipate their true motivations?

The problem for conspiracy theorists will always be the construction of the proper context for a conspiracy - one that bridges the world in which us peasants live with the one the power elite occupy.  Amusingly, the power elite have the same problem with disproving conspiracies: too detailed a context for this attack raises more questions than it answers.  Gaps exist in all the explanations of 9/11, and they thrive or dwindel into obscurity based not on Occam's Razor or explanatory power but rather on the size of the megaphone used to convey them.

Thank God for the internet challenging popular media hegemony over the scope of public interest, such as the cursory treatment of conspiracy theories we saw in Time (the fact that they're acknowledging them at all is curious).  I imagine that every September 11th, from now on, we will stage this kind of mainstream ceremonial purging of "conspiracy theories" from the collective mind.  It's an exercise in social hygiene, routine maintainace on a public debate that needs management and occasional clean-up.  The important part is not to address concerns or gaps in the official conspiracy theory, but to reaffirm how we do things in our society - to get the collective mind right.  Indeed, I even see liberals all over the place chastising doubters of the official story - not because the doubts are based on inaccuracies or errors, but because such doubts of officialdom hurt the legitimacy of the political machinery they're trying so desperately to dominate.

How do we deal with not simply a complex world but also one full of unanswered questions?  One way is to get clear on what we don't know.  There are holes in all the competing explanations of 9/11, including the official conspiracy theory.  A larger worldview of politics in general tends to fill in the gaps, and that's fine insofar as it goes.  But we also need to acknowledge that as an assumption, and maintain an open mind towards things.

Lazy thinking isn't considering alternative explanations for 9/11, no matter how outrageous they may be.  Lazy thinking is accepting spoonfed soundbites because it's easier to direct our confusion and anger in a prepackaged manner.  Lazy thinking causes us to oversimplify a complex foreign policy history going back at least half a century, to the point that Saddam Hussein, the most secular of the arabs, is suddenly an Islamic fundamentalist.  The only thing that makes that conspiracy more fundamentally believable than explosive charges planted in the World Trade Center or an Air Force stand down order is the degree of unfamiliarity with which we're comfortable on matters of foreign affairs.  To acknowledge our unfamiliarity with domestic political realities is too painful - better to let the experts tell us what to think on that.

The sad part is that it costs us nothing to keep an open mind about 9/11, but most people cannot bear to be outside the mainstream on such a painful issue.  This brings to mind Gatto's analysis of public schooling as, in part, a scheme to socialize citizens to conformist thinking.  Indeed, he tackles the issue of conspiracy along the same lines, and though he's addressing the history and forces at play in public education, his warnings apply to 9/11 conspiracy as well:
<blockquote>If you obsess about conspiracy, what you’ll fail to see is that we are held fast by a form of highly abstract thinking fully concretized in human institutions which has grown beyond the power of the managers of these institutions to control. If there is a way out of the trap we’re in, it won’t be by removing some bad guys and replacing them with good guys.</blockquote>
This is the problem I have with the "Bush let it happen" mentality, or the "Get the terrorists" mentality.  They ignore a greater context that is not just incidental to our global order but <strong>born of it, bred within it, and operating as a function of it</strong>. 9/11 didn't happen because of Bush, terrorists, or any of that - events have been building up to it for quite some time.  You were either aware of it, or you weren't - but there's no one person we can blame. Even if there was, that wouldn't solve the problem.

If you seek to challenge this order, the institutional order that has led to tragedy, and really uncover the "evil", the first thing you must do is challenge the assumptions you've been led to make on behalf of this larger system.  This includes skepticism towards theories outside the officially sanctioned wisdom - but also skepticism towards the official wisdom as well.  All facts, all possibilities, should be on the table.  We need 400 million independent investigators, not one commission, if we care about the truth and not simply outward conformity.
