--- 
wordpress_id: 380
title: Archetypes Gathering begins
wordpress_url: http://blog.6thdensity.net/?p=380
layout: post
---
My friend Tobey and I made the trip yesterday from Virginia to Louisville for the Archetypes Gathering sponsored by <a href="http://www.llresearch.org">L/L Research</a>.  We are going to be studying the system of archetypes as discussed in the Law of One series.  We're hanging out at the L/L house right now before we head to the place we'll be holding this weekend's festivities.  So far I've had a great time talking with people - this gathering is only 10-12 people, and we'll be intimately exploring the archetypical mind and the principles of spiritual evolution.  I plan to record our proceedings and use this blog to document any progress we make.

This evening we discussed the general aspects of the Archetypical Mind of the Logos.  I'd like to blog more about this and explain in greater detail my understanding of these concepts, but right now I'm trying to participate and pay attention as much as possible.  Suffice to say: the Archetypical Mind is a resource available to us humans in third density for grasping the nature of spiritual evolution in our incarnations.  We are focusing upon the images of the Major Arcana of the Tarot, since these images serve as representations of the different aspects and tones of this all-mind.

The archetypes are broken up into 3 groups of seven, with a remaining 22nd archetype.  There is a set of seven cards that represent the mind, seven for the body, and seven for the spirit.  For each of these octaves of archetypes (i.e. sets of seven images) the particular position of a card in the octave designates the role of that archetype within the mind, body, or spirit.  These roles or functions are Matrix, Potentiator, Catalyst, Experience, Significator, Transformation, and Great Way.  The final archetype is that of the Choice, which represents the choice of polarity given to each entity in our world as they grow in spiritual understanding.

That polarity of which I speak is the choice of negativity or positivity (more crudely explained as good and evil), the two ways one may use energy to do work in the higher densities through which spiritual evolution takes a person.  Because our experience in this third density material evolution is uniquely tied into the Choice, the archetypes are important expressions of the "builded structure of energy expenditures".  In other words, the system of archetypes serve as a tool or resource of the greater mind available to all that delineates the nature of our journey within the Creation.

In our attempt to understand the concepts represented by the images, we are delving into a rich and mysterious set of information.  It has proven both frustrating and interesting: frustrating because one's interpretation of the archetypes is quite personal and unique by the very nature of the intuitive faculties they call forth; interesting because many find things in the images and the concepts that I did not see before.  I'd like to use this blog to record my exploration of the Archetypical Mind with this group, but I don't want to dwell on writing a primer about all this stuff for my readers who are not familiar with the Law of One.  Therefore, please ask questions in the comments if you are unclear, or better yet, engage in the discussions at <a href="http://delta.bring4th.org">Bring4th forums</a>.  You can find out more about the Law of One sessions which serve as the basis for our study at the <a href="http://llresearch.org">L/L Research library</a>.
