--- 
wordpress_id: 468
title: "Human Nature: the Fulcrum of Political Polarity"
wordpress_url: http://blog.6thdensity.net/?p=468
layout: post
---
<p>INTRODUCTORY NOTE: <i>This essay was originally written for the now defunct blog "Wrong Thinking Girl".</i></p><p>It seems appropriate somehow to christen this blog with a broad analysis of <a href="http://rightthinkinggirl.com">RightThinkingGirl</a>'s philosophy.  This should set the tone for the blog, and give a good insight into why we started it.  RTG has gotten people thinking, and that's a good thing - what we want to do here is highlight that thinking, or at least that which occurs on the other end of the spectrum.</p>
<p>To the extent that RTG delves into politics, we need to start with her primary biases and assumptions.  Politics, even at its worst, results from a particular understanding of sociology, psychology, and the general attitudes one holds towards the human animal.  Defining the scope of acceptable behavior and deincentivizing antisocial behavior takes place within the context of what one should expect from one's fellow man.  To the extent that people are motivated to realize their vision of society via politics, this axiomatic understanding of human nature is primary. After all, if you're going to engineer people, you gotta have an ideal towards which to aspire.</p>
<p>So, let's propose that an understanding of "human nature" is the essential foundation of politics, and that the Right and the Left come down on their respective sides because of a core difference in approach.  What does this mean for the debate occuring across the no-man's-land of the status quo establishment?  What <em>are </em>these two different sides (if they're even reducable to two sides)?  And, most importantly, where does RTG's position wind up in the end?  If we're going to get to the root of the Right/Left dichotomy, let's be sure we've given each side a chance.</p>
<p><!--more-->The death penalty debate, as it turns out, is the great proving ground for one's views on human nature.  True to form, RTG lays out her position taking a no-apologies stance on state executions. Her thesis:</p>
<blockquote>
<p>Death penalty opponents will focus on systematic concerns.  They will claim we might execute an innocent man (though we never have.)  They will claim that they can be good parents while still in prison.   They will make all kinds of claims that are basically static to avoid the real issue: that <strong>people who commit these kinds of awful crimes are not just like you and me - they are, quite simply, subhuman</strong>.</p>
</blockquote>
<p>I can't speak for the other liberals here, but my beef with the death penalty is independent of whether or not the state gets it wrong from time to time (it would be silly to suggest it doesn't).  Rather,  I think it's dangerous whenever somebody invokes the language of classifying people's entitlement to life according to their essential, intangible "humanity".  The state simply doesn't have a good record in this regard,  from the history of slavery to the Holocaust to  historical attitudes towards mental illness.   All of these  horrors were visited upon mankind  by the state - backed up by  a belief that some people are not human.  It's easy to see why this occurs - sheer convenience in the case of tough, complex situations in society.  Yet, in each case, we eventually discovered that those judgments were unwarranted.</p>
<p>Now, I understand that somebody who has committed a horrendous crime deserves sanction.  And I'm not arguing that a person who has done something monsterous is on the same level with the innocent vicitms of slavery or eugenics.  I'm talking about how we as a society deal with the people whom, for whatever reason, we find unacceptable.  Because how we respond to these problems says a lot about ourselves and our progress as a species, it's very important that we not force the blood to boil in typical conservative form.</p>
<p>Of course, invoking emotions is the entire conservative modus operandi, as RTG goes to copious length to describe the crimes. As she tells us the story of these actions, it's clear that she's affected by them.  I appreciate even the half hearted attempt to put oneself in what is clearly a sick person's shoes, but keep in mind that RTG is an accomplished fiction writer and fiction is all about the emotional point:</p>
<blockquote>
<p>Imagine for a moment, the decision to do such a thing.  Imagine going through the house to find duct tape.  You storm into the kitchen,  shake open the drawers.  You have tape in your hand.  You make the decision to walk into the room where the baby is crying or sleeping, or gurgling at a mobile.   Then you grab him.  You pick him up.  He’s tiny, barely seven pounds, and he wears a white diaper.  You lay him down on the bed.  You grab that tiny arm and place it over his chest.  And you tape his arm down.  By now, that four day old baby would have been crying.  He would not have liked having his arm bound to his body.  Sticky tape on that sweet, tender, velvety soft skin.   More tape wrapped tightly around his tiny rib cage.  Then the tape covers his sweet little mouth.  Covers his nose.  He can’t breathe.  His mom wraps the tape over his eyes, getting his eyelashes stuck to the tape.  Imagine yourself doing that to a four day old baby.  Your own baby.</p>
<p>...</p>
<p>And that story, sadly, isn’t so very unique.  On that same Death Row is Darlie Routier who stabbed her two boys to death.  One was six, one was seven.  Stabbed them.  Then said she slept through it all - even though they were literally less than two feet from her.  No, what this woman did was this: she got up from the sofa, went into the kitchen and got a large kitchen knife, and then went back into the living room.  Her boys were sleeping.  Imagine how peaceful they looked.  Little boys asleep after a long day of playing outside.  Cute little boys.  <em>Her own boys</em>.  And she stood over her youngest one first, and plunged that knife into his little back.  She hacked into his six year old body so hard that the knife went all the way through his body and stuck in the carpet.</p>
<p>Cathy Henderson is another one.  She killed a three-month old baby.  This one wasn’t her own child.  She claims she was just going to sell him - but she ended up dropping him on his head, then burried him in a shallow grave and fled the state.   She actually admitted that she was going to sell this child.</p>
</blockquote>
<p>I share the digust you must be feeling after reading these stories. They leave you feeling totally empty, the sacredness of life strewn about your mind.  It's incomprehensible.</p>
<p>I expect people to be scared, confused, and horrified by those narratives.  But scared, confused, horrified people can act in incredibly self-defeating and overblown ways. Unfortunately, when we call upon the state to use its immense force, we are invoking <a href="http://www.fff.org/freedom/1094f.asp">the single most destructive force in history</a> - far more destructive or horrifying than anything these women could have done. Indeed, the whole reason we ask the state to moderate justice is because it claims to act dispassionately and with utmost regard for the most just remedy. Is it so wrong to insist on some deep thinking before we use it out of anger and revulsion?  Or is blind anger without reflection the only way we're going to get the gumption to commit same types of acts these people have been accused of committing?</p>
<p>Because as much as RTG and others want to cast these people out society, out of life, and out of their own minds, the fact remains that <strong>they are people</strong>.  They are human beings - yes, like you and me. They had mothers and fathers.  They were babies once.  They had hopes and dreams.  Isn't that sad - isn't that a tragedy too?  Isn't that part of the story?</p>
<p>Apologists for the death penalty want us to only consider the victim's families.  When in the course of officially prosecuting state duties is it ever wise to serve one group of people over others? Isn't there a society to think about here?</p>
<p>Don't just put yourself in the shoes of these murderers as they are offending nature and humanity. Follow them through their whole life.  Don't just ask how they could do such a horrible thing - look at the path that led them there.  They are showing us something that lurks in our hearts, a potential that we have within us as well.  Now THAT's something painful to think about.  Because there's a very good reason we can't imagine doing those things: we don't want to. Yet, in the name of our impatience with the dark side of ourselves, we are calling on perhaps the biggest, most heartless, most bloody killer of all time!</p>
<p>Conservatives have a long history of not wanting to consider the complexity of human beings, seeing whatever lot the masses happen to find themselves in as the way God intended it. While <a href="http://en.wikipedia.org/wiki/Left-wing_politics">the Left</a> - from its very beginnings in the French Revolution - have campaigned for the equality of mankind, seeking to cast down the caste-like social distinctions of the feudal and post-feudal capitalist systems, <a href="http://en.wikipedia.org/wiki/Right-wing_politics">the Right</a> have consistently questioned the need for such bothersome philosophizing and speculation. Seeking the comfort and familiarity of caste-like social systems where people knew their place, they saw the Left as mere rabble-rousers.  As a friend of mine once said, "some things just aren't deep". This is often the implicit rallying cry of an ideology which seeks to preserve the old order, with a healthy side order of ignorant bliss. Delving too deep is dangerous! Better to just pay your taxes, keep your head down, and rally around the latest execution.</p>
<p>Humans are complex.  They are deep.  They haven't always been understood, and I have a hard time accepting that we understand them now.  That's why I'm on the Left: I believe we have a lot to learn, and that we should try to learn as a society.  It's too easy to dispense of elements that we find inconvenient - to put them in a category separate from us.  It's not a truth; it's a defense mechanism to hide a facet of human nature from us. Leftists are interested in the full scope of human nature: society should serve the humans that actually exist, not force humans into a mold that doesn't fit or eradicate them like a cancer. Hopefully over the course of this blog you will see other opinions on what it means to be on the Left - especially those who, unlike me, support the state's monopoly over force.</p>
<p>Here's the point: society will always have frontiers of fear and misunderstanding, and the deepest abyss of the human heart may always be unknowable.  But extinguishing life doesn't remedy anything - it only continues the pointless violence.  It does this, furthermore, by empowering the biggest killer by far in human history. Death is not a currency with which to pay back a debt, nor is it a mechanism for teaching a lesson. By promoting the death penalty, RTG is simply showing that matters of human interest are simply too complex to be dealt with in a thoughtful manner and must therefore be swept from the healthy mind.  We'd do better to ponder our own weaknesses and savagery - especially with regards to the state - than to simply isolate cases where human nature has failed us and purge these symptoms of a deeper collective problem.</p>
<p>The Left, to her chagrin, will continue to fight for a deeper understanding of human nature, rather than the current established order thrown into some sort of arbitrarily sharper relief.  It's easy to play rear guard to human intellectual and philosophical progress - you never have to admit any fallability.  But as a society, we are as a deep as we want to be - and this is where the Left and the Right really part ways.  The Left sees the individual in the context of a complex, constantly puzzling world.  The Right fights for an easy calculation of the human experience.  Both stances are no more or less valid, true, but when dealing with matters of war and peace, life and death, and human dignity, one should make no mistake which side is open to the evidence of the mind and which rules from the gut.</p>
