--- 
wordpress_id: 656
title: Garrison Keillor a Bigot?
wordpress_url: http://blog.6thdensity.net/?p=656
layout: post
---
It's possible.  But it's going to take more than <a href="http://www.salon.com/opinion/feature/2007/03/14/keillor/">one article</a> for me to make that judgment.  And it's going to have to say things that haven't been jokes a million times over on Will and Grace.  Battlepanda <a href="http://battlepanda.blogspot.com/2007/03/garrison-keillor-creep.html">losing her shit</a> over this doesn't surprise me.  Dan Savage's <a href="http://www.thestranger.com/blog/2007/03/fuck_garrison_keillor">even more over the top reaction</a> does, since he typically exhibits a thicker skin than most.

Of course, everybody's entitled to their opinion, and mine must be weighed by the fact that I love A Prairie Home Companion and grew up with it.  It's not just funny and entertaining in a gentle way; it reminds me of childhood, honestly.  So bear that in mind whilst I defend Garry's honor.

Battlepanda is incensed by the way Keillor has supposedly legitimated gay bashing:
<blockquote>APHC is satire, but Keillor is not Borat. Borat is Sacha Baron-Cohen saying "look at these people and how ridiculous they are. What a bunch of ignorant creeps." Keillor is saying "look at these people and how ridiculous they are. Aren't they adorable? Aren't they better people in their simple, stoic way then we'll ever be?" By slipping in several some really ugly assumptions about gay people in the same down-home hokey manner as if he's just making fun of big-city folks with their blackberries, Keillor is saying that, whether or not he personally shares those values**, they are not beyond the pale in our society. Keillor would never be as gauche as to complain about "welfare queens in Cadillacs" or tell "she's on PMS" jokes even as he make cracks about gay couples sharing wardrobes living in overdecorated apartments with tiny dogs.</blockquote>
I think she misunderstands Keillor's humor.  That show makes fun of every stereotype you can think of, and some you can't (I have absolutely no idea what a Swedish stereotype is supposed to be, but the impersonations are still funny).  The whole idea behind the show IMHO is that Keillor's gentle enough to get away with a lot of hard truths and cutting perceptions.  He's a soothing personality in large part because he <em>doesn't</em> pass judgment or condemn people, but rather merely observes what's going on.  Any conclusions are usually the audience's.

Now, I realize this is from an article, not the show.  Nor do I believe he framed his thesis well. Let the record reflect the offending excerpt:
<blockquote>The country has come to accept stereotypical gay men -- sardonic fellows with fussy hair who live in over-decorated apartments with a striped sofa and a small weird dog and who worship campy performers and go in for flamboyance now and then themselves. If they want to be accepted as couples and daddies, however, the flamboyance may have to be brought under control. Parents are supposed to stand in back and not wear chartreuse pants and black polka-dot shirts. That's for the kids. It's their show.</blockquote>
Of course this could be offensive.  Humor often is if it's really insightful.  The question here is what exactly he's being insightful about.  I'd argue it isn't gay marriage qua gay marriage.
<ol>
	<li>He clearly states (earlier in the article and builds to this point) that the problem is not gay parenting but self-involved parenting.  That sounds like the voice of experience, as many angry bloggers have pointed out his failed marriages.  They just assume that, since he's making fun of a gay stereotype, he must be mean spirited and not speaking from a place of honesty and humility.</li>
	<li>He clearly states that the stereotype he's invoking is just that: stereotypical gay men, not real life ones, let alone all of them.  If he wanted to say "all gay men have fussy hair", he could have.  His point, if I understand it correctly, is that America has come to embrace <em>even the ugly stereotype</em>.  Since bigotry is no longer an insurmountable challenge to same sex couples who want to raise children, homosexual couples are going to have to cope with a challenge that, until now, has largely been reserved for heterosexual couples.</li>
</ol>
Sure, there's some stuff in there that comes out sounding bad.  Shame on him.  But I don't think it comes off as bigotry.  It would be one thing if he singled out gay men for satire, but that can hardly be argued.  If anything, I thought his views on parenting were refreshingly insightful and inclusive - "these are your problems now, too" he's essentially saying.  I didn't find his comments on the gay stereotype particularly funny, but they hardly seem hurtful (though I am not, in fact, gay).

Battlepanda wrote at length about how much his stereotypical attack on gay men was a sign of bigotry.  But if that's bigotry, then why aren't all the Swedes writing angry letters?  Because they <em>agree</em> with their portrayals?  Dan Savage doesn't do much better:
<blockquote>And what if some gay parents are flamboyant? Flamers, even? So what? What if some gay parents have striped sofas and over-decorated apartments and wear chartreuse pants and make their kids write book reports on <em>All About Eve</em>? The idea that effeminate gay men can’t or shouldn’t be parents is bullshit, just another iteration of the same old anti-gay double standard the right trots out.</blockquote>
By making this out to be all about gay people, they're missing the larger point he was making: people need to put their children first.  It applies equally to heterosexual and homosexual couples.  I imagine that observation is the voice of regret and experience speaking on his part, since as both above bloggers point out, he's had his share of failed marriages. BUT, if he's not attacking gay parents but rather addressing them on the same terms as straight parents, then there's no double standard and no bigotry.
Am I way off base here?
