--- 
wordpress_id: 648
title: RESTful Richmond featuring Ryan
wordpress_url: http://blog.6thdensity.net/?p=648
layout: post
---
<a href="http://www.flickr.com/photos/bigfleet/tags/cvreg/"><img title="Ryan presenting to our group" alt="Ryan presenting to our group" style="margin: 3px; float: left" src="http://farm1.static.flickr.com/158/423307182_c626a1243f_m.jpg" /></a><a href="http://ryandaigle.com">Ryan Daigle</a> spoke at the <a href="http://cvreg.org">Central Virginia Ruby Enthusiasts Group</a> March <a href="http://cvreg.org/2007/3/15/march-madness-er-meeting-minutes">meeting</a> on <a href="http://ryandaigle.com/articles/2007/3/14/rest-activeresource" /><a href="http://ryandaigle.com/articles/2007/3/14/rest-activeresource">REST & ActiveResource</a>.  It was a great presentation that made many of the core concepts of REST far more concrete than they were before.  You can download a PDF of the presentation <a href="http://ryandaigle.com/assets/2007/3/14/REST_ARes.pdf">here</a>.  Also, check out <a href="http://contactsapi.com">ContactsAPI</a>, which is a project Ryan started to demonstrate the ways <a href="http://wiki.rubyonrails.org/rails/pages/ActiveResource">ActiveResource</a> can be used to achieve RESTful Rails models.

<a href="http://www.flickr.com/photos/bigfleet/tags/cvreg/"><img style="margin: 3px; float: right" title="Mel (left) and I discussing Bookmarker" src="http://farm1.static.flickr.com/147/423307318_acb4f60454_m.jpg" /></a>I'm hoping to have my <a href="http://cvreg.org/projects/bookmarker">Bookmarker</a> project done in time for the April meeting so I can give a short announcement / demo so that people can start banging on it.  There's even talk of a training course and documentation materials for it.  All I can say at this moment is that I'm trying to keep my eyes on the prize.

Also, <a href="http://upcoming.org/event/155002/">plan on attending May's meeting</a>, where CVREG will be partnering with the <a href="http://www.richmondjug.com/">Richmond Java Users Group</a> to host a presentation by <a href="http://www.relevancellc.com/about">Stu Halloway</a> on the subject of his new book, <a href="http://www.pragmaticprogrammer.com/titles/fr_rails4java/">Rails for Java Developers</a>.
