destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    false
markdown:    maruku
permalink:   date
paginate:    15
site_title:  Social Memory Complex
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex