destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   pretty
site_title:  Social Memory Complex
sass:        true
haml:        true
paginate:    10
post_defaults:
  layout: post