destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    false
markdown:    maruku
permalink: /:year/:month/:title.html
paginate:    15
site_title:  Social Memory Complex
sass: true
haml: true
post_defaults:
  layout: post