--- 
wordpress_id: 145
title: Government priorities revealed at last...
wordpress_url: http://blog.6thdensity.net/?p=145
layout: post
---
<p>Regular reader(s) of SMC know that I am anti-government.  Not satisfied with simply having a small government, I sieze every opportunity to demonstrate the larger point: that the philosophy of force that informs the institution of the state is a bad way of doing the human business of life, trade, and stuff like that.  It should not have surprised you all that I, like many libertarian bloggers, took the failed government response to Katrina as a sort of proof of the libertarian argument.  And I even <a href="">hinted</a> that there was more to the mess than simple ineptitude.</p><p>All I can say is that it <a href="http://www.reason.com/hod/dk091005.shtml">appears</a> that the screeching of the alarmists on the libertarian front was sadly correct:<blockquote>In the nearly two weeks since Hurricane Katrina, the government of New Orleans has devolved from its traditional status as an elective kleptocracy into something far more dangerous: an anarcho-tyranny that refuses to protect the public from criminals while preventing people from protecting themselves. At the orders of New Orleans Mayor Ray Nagin, the New Orleans Police, the National Guard, the Oklahoma National Guard, and U.S. Marshals have begun breaking into homes at gunpoint, confiscating their lawfully-owned firearms, and evicting the residents. "No one is allowed to be armed. We're going to take all the guns," says P. Edwin Compass III, the superintendent of police.</blockquote></p><p>Now, disarming a populace is abhorrent, but doing so when armed gangs are preying on the populace is just sick.  I was glad to hear that the Army troops under General Honore are <a href="http://www.breitbart.com/news/2005/09/11/D8CI3A8O0.html">not participating in the forcible removal</a> of NOLA citizens, though - so far everything Honore has done in this response has been outstanding.  When leadership was needed, he <a href="http://www.cnn.com/2005/US/09/02/honore.profile/">came in and provided it</a>.  Thank God somebody involved in the gov't has some common sense and an idea of the urgency at hand during the whole disaster; otherwise I shrink from pondering what would have happened.</p><p>Now there more FEMA horror stories, not just involving the <a href="http://blog.6thdensity.net/?p=137">refusal of aid to refugees</a>, but <a href="http://simbaud.blogspot.com/2005/09/camps.html">FEMA</a> <a href="http://www.abovetopsecret.com/forum/fema.html">camps</a> that seem more like detainment centers!<blockquote>We then started lugging in our food products. The foods I had purchased were mainly snacks, but my mother - God bless her soul - had gone all out with fresh vegetables, fruits, canned goods, breakfast cereals, rice, and pancake fixings. That's when we got the next message: They will not be able to use the kitchen.

Excuse me? I asked incredulously.

FEMA will not allow any of the kitchen facilities in any of the cabins to be used by the occupants due to fire hazards. FEMA will deliver meals to the cabins. The refugees will be given two meals per day by FEMA. They will not be able to cook. In fact, the "host" goes on to explain, some churches had already enquired about whether they could come in on weekends and fix meals for the people staying in their cabin. FEMA won't allow it because there could be a situation where one cabin gets steaks and another gets hot dogs - and...

it could cause a riot.

It gets worse.

He then precedes to tell us that some churches had already enquired into whether they could send a van or bus on Sundays to pick up any occupants of their cabins who might be interested in attending church. FEMA will not allow this. The occupants of the camp cannot leave the camp for any reason. If they leave the camp they may never return. They will be issued FEMA identification cards and "a sum of money" and they will remain within the camp for the next 5 months.

My son looks at me and mumbles "Welcome to Krakow."</blockquote></p><p>The more FEMA tries to "help", the more I think their sole purpose is to humiliate the American people.  So it only makes sense that FEMA is part of the United States Gov't and the thugs that run it.</p><p>Hattip to Vince (you got a website to which I can link?).</p>
