--- 
wordpress_id: 17
title: What it's like to be a woman and why men should care
wordpress_url: http://blog.6thdensity.net/?p=17
layout: post
---
My fellow libertarian blogger <a href="http://jacquelinepassey.blogs.com">Jacqueline</a> has a great post about <a href="http://jacquelinepassey.blogs.com/blog/2005/04/what_its_like_t.html">What it's like to be a woman and why men should care</a>.  It's something in which I'm particularly interested because of my experience as a man and as a boyfriend/fiance.  She makes some compelling observations about the condition of women in today's society:<blockquote>I and almost all my female friends have been sexually assaulted at some time in our lives, ranging from the very common but minor unwanted grabbing or pinching of body parts, to the less common but unfortunately not rare drug- or alcohol-facilitated date rape, to the thankfully much rarer violent assault and forcible rape.  And even despite its relative rareness, I personally have several female friends who have been brutally raped, including one fairly recent incident.  Many women are also sexually abused as children, and the abusers are almost always men.

I know that this behavior is not representative of how the majority of men act.  Unfortunately, though, it seems that the men who do act this way each victimize several women.  So <b>a minority of men are assaulting a majority of women, ensuring that almost all women, through either their own personal experiences or hearing about the personal experiences of their friends, have good reason to feel afraid of men</b>.</blockquote>

This is a problem for us men, most definately, not just because it makes it that much more difficult to be trusted in a new relationship, but also because it requires us to think in terms with which we're uncomfortable.  I think I speak myself and most guys (at least, that I know) when I say that vulnerability is a disturbing concept to us.  Some of us become defensive and protective of things we value, some become frightened, timid, and partially emasculated, whereas others embrace it by putting themselves in dangerous situations constantly.  

My personal coping mechanism (one shared by many of my male - and female - friends) is to try and ignore the condition of vulnerability.  This makes it particularly difficult for me to understand where my fiance is coming from.  I remember back in college she would get upset that I would be loathe to walk her back to her dorm at night, which was across the campus.  It just didn't occur to me that she would be in any danger, because I'm not accustomed to thinking in those terms.  On the other hand, she's thinking that she's alone and vulnerable to sexual assult.  How exactly do I understand that?

I suppose on the one hand, I need to come to terms with my own vulnerability.  While I do think some women worry unnecessarily (it is in their stereotypical nature), some men like me probably don't think about worst case scenarios enough.  Lord knows I've walked in some pretty sketch parts of town before and managed to avoid violence somehow - certainly not by thinking ahead.  But it's difficult for me to think about danger because there's danger everywhere.  I don't want to be consumed with worry, and moreover I don't want my fiance to worry.  I do want to be there to protect her, of course, but how do I anticipate threats without becoming a worry wart?  

It's a difficult balance for guys to achieve, whereas I suppose one could make the argument that women are conditioned by nature and life to be vulnerable and to worry - after all, I'm sure the history of human male/female relationships has involved violence or compulsion in probably a majority of cases.  Let's be honest: the repression of the male impulse to dominate the female, and social support for female resistance to this impulse, is a relatively recent phenomenon in the long annals of human history.  I'm sure there's a lot of lingering societal memory in this area.

A complicating factor in all this is how the experience of men vis a vis women has changed.  Jacqueline definately illustrates the disconnect here:<blockquote>When women go on dates, we have to worry about getting raped.  When we agree to dance with a man at a bar or party we have to worry that he's going to take that as an invitation to then molest us.  When we start dating a new man, the first few times we get into his car, invite him into our homes, or accept an invitation into his home, we have that twinge of worry, "Is he going to kill me?" 

In comparison, guys, what's *your* biggest realistic fear about dating?  That a woman might reject you and hurt your feelings?  Well, we've got all your same worries of rejection plus the fear of assault on top of that.  So do you see why many women are so cautious about dating or otherwise allowing themselves to be vulnerable to men?</blockquote><p>Now, let's concede one point off the bat: Jackie has a point, no doubt.  Concerns about being assaulted trump the desire to be accepted any day.  But that doesn't explain the entire dynamic in dating whatsoever.  The bottom line is that in today's dating world, I and many of my male friends believe that for the most part, most of the time, <b>women hold the majority of the power</b>.  With the sexual revolution being fourty years old, society is quite clear that a woman does not need to get a man to marry her to have sex.  There are plenty of options for women to avoid many of the consequences of promiscuity: most importantly, pregnancy.  Therefore, men and women are on more or less equal terms as far as what they can expect from a sexual relationship.  However, it is still almost always incumbent on the man to initiate relationships on every level, from the date to the bedroom.  This puts women in a position where they have the power to accept or reject advances.  In the case where there is no physical danger to either person, men really do take the first emotional risks.</p>

I'm sure this is changing, but a woman's sense of vulnerability is one reason why it may not be changing as quickly as many of us egalitarian men would like.  And because women are in such a position to reject men in a way that goes against the historically (not to mention biologically) assertive role of men, that may play into some of the psychology behind sexual assaulters.  Clearly power is an important concept in the mentality of the sexual predator.  Note that I am in no way, shape, or form suggesting that this theoretical female advantage <i>causes</i> the instances of assault - I am not blaming the victim - but I am trying to understand the total social dynamic of the male / female relationship.

Understanding, as usual, is the key, after all.  I don't think many men understand how the liberalization of womens' roles in the world has made their lives that much more fulfilling, interesting, and complete.  A woman is now able to play such a more comprehensive role in a man's life now that the superficial barriers of history have been erased - and the formerly exclusive male roles are enriched by the female influence.  Fostering a society where a balance between the sexes is struck more evenly more of the time will help men and women appreciate the unique experiences of the other gender more often.  Jackie correctly points out that this has to start with the elimination of violence from the equation.  As men, we can't really take charge of the situation in a meaningful way until we understand the condition of vulnerability.  Hell, that may even necessitate us getting in touch with our "feminine side" in order to understand the female condition appropriately.

But if you start decorating your room in pink, Matt, you will no longer be my best man.
