--- 
wordpress_id: 503
title: Activism on Rails
wordpress_url: http://blog.6thdensity.net/?p=503
layout: post
---
<p>Via the impeccably relevant <a href="http://www.bradspangler.com/blog/archives/462">Brad Spangler</a>, I've learned that there is a <a href="http://rubyonrails.org">Rails</a> project to build a web application for social organizing and direct democracy called <a href="http://cats.revolt.org/cats-vii/crabgrass/one-pager/">Crabgrass</a>.  If you're a Rails developer who wants to see the web become a more productive venue for political activism, I strongly urge you to volunteer.  And if you're experienced in web development but haven't given Rails a try yet, here's your chance (<a title="DHH writes a blog in 15 minutes" href="http://media.rubyonrails.org/video/rails_take2_with_sound.mov">this video</a> should pique your interest).</p>
<blockquote><p>Social movements have grown more adept at using the web to communicate publicly. However, we could still use a lot of help in communicating amongst ourselves. In particular, we need the ability to communicate securely; the ability to make decisions between groups and networks that are geographically disbursed; and the ability to have a decision process that is easy to understand, transparent, and directly democratic.</p></blockquote>
<p>The things they want to do, including building mechanisms for networked relationship tracking and decision making, sound awesome and quite worthwhile.  Actually, the group should also make sure they take advantage of Rails's features to roll out functionality as it becomes available, <a href="http://agilemanifesto.org/">agile-style</a>, because it will be vital to make sure this really streamlines the activist's workflow to fully empower people.  Hopefully I'll be able to contibute to this (and make time for it).</p><p>But really, they had me at this sentence: "The social networking phenomenon holds much promise, but it is clear that the revolution will not be hosted by myspace."  Word.
</p>
