--- 
wordpress_id: 499
title: Israel as America's Hofjuden
wordpress_url: http://blog.6thdensity.net/?p=499
layout: post
---
<p>I've heard a lot about how Israel's recent attack on Lebanon was a preemptive strike to set the stage for a U.S. attack on Iran.  <a href="http://www.alternet.org/story/40797/">This AlterNet article</a> documents much of the planning for the campaign against Hezbollah, arguing that it was largely seen as serving America more than Israel.  It makes the argument that although Israel is often accused of manipulating U.S. policies (see articles at <a href="http://en.wikipedia.org/wiki/AIPAC#Controversies">Wikipedia</a> and <a href="http://www.antiwar.com/cole/?articleid=3467">Antiwar.com</a>), the door may swing both ways.</p>
<p>This implies that those who set the foreign policy agenda are acting on interests outside of either Israel's or those of the U.S., to say nothing of the rest of the world.  Certainly <a href="http://www.alertnet.org/thenews/newsdesk/L11918874.htm">the war is not popular</a> in Israel, and <a href="http://www.haaretz.com/hasen/spages/741404.html">demonstrations</a> against it have united jews and arabs.  The most disturbing part of the article, however, was the author's comparison of Israel's long-running role as the U.S. proxy in the middle east with the historical role of "<a href="http://en.wikipedia.org/wiki/Court_Jew">court jews</a>" in European monarchies.  The parallels between the elitism of the old absolutists and that of our current leaders are disgusting:</p>
<blockquote><p>One of the more unsettling aspects of the broad support in Washington for the use of Israel as U.S. proxy in the Middle East is how closely it corresponds to historic anti-Semitism. In past centuries, the ruling elite of European countries would, in return for granting limited religious and cultural autonomy, established certain individuals in the Jewish community as the visible agents of the oppressive social order, such as tax collectors and moneylenders. When the population threatened to rise up against the ruling elite, the rulers could then blame the Jews, channeling the wrath of an exploited people against convenient scapegoats. The resulting pogroms and waves of repression took place throughout the Jewish Diaspora.</p>
<p>Zionists hoped to break this cycle by creating a Jewish nation-state where Jews would no longer be dependent on the ruling elite of a given country. The tragic irony is that, by using Israel to wage proxy war to promote U.S. hegemony in the region, this cycle is being perpetuated on a global scale. This latest orgy of American-inspired Israeli violence has led to a dangerous upsurge in anti-Semitism in the Middle East and throughout the world. In the United States, many critics of U.S. policy are blaming "the Zionist lobby" for U.S. support for Israel's attacks on Lebanon rather than the Bush administration and its bipartisan congressional allies who encouraged Israel to wage war on Lebanon in the first place.</p></blockquote>
<p>How utterly sad.  If jews were looking for a truly independent and secure homeland, they should have settled somewhere where they were not beholden to others' interests.  Instead, they relied on an outside international bureaucracy, unanswerable to any democratic governance, to establish a state by fiat.  Displacing millions of natives, they made themselves a hundred years worth of enemies.  Once again they have to rely on outside authority in order to simply exist.</p>
<p>It is this fundamentally imbalanced situation that is being perpetuated by right-wing belligerence and bellicosity.  The powers that be on both sides realize there's no explotative power in peace.  So the political intrigue continues.  I'm sure this involves equal measures of Israel subservience to U.S. interests and Israeli manipulation of U.S. interests.  But I doubt anybody could argue that the jewish people, as a whole, are somehow better off now.
</p>
