--- 
wordpress_id: 484
title: ThreadSpinner coming along
wordpress_url: http://blog.6thdensity.net/?p=484
layout: post
---
<p>My <a href="http://rubyonrails.com">Rails</a> <a href="http://summerofrails.org/">project</a>, dubbed ThreadSpinner, is coming along - slowly but surely.  I was worried that my current assignment at my day job would hamper my enthusiasm to code in my free time.   I just came off a very interesting Rails project for a client and I'm not sure I would have ever learned <a href="http://ruby-lang.org">Ruby</a> or the Rails framework as quickly on my own.  Getting paid to learn a fun language is quite a motivation.  However, I'm finding that coding is becoming a cool pasttime, and now that I've cleaned up my office I'm energized about making ThreadSpinner something interesting and exciting!</p>
<p>I've got a basic threaded forum working (thanks to <a href="http://www.railtie.net/articles/2006/02/05/rails-acts_as_threaded-plugin">Bob</a> <a href="http://www.railtie.net/articles/2006/03/31/implement-acts_as_threaded-without-a-plugin">Silva</a>) so the fundamental structure of what I want to do is now there.  At this point the real work begins: I need to rework this structure and functionality into something that allows "posts" to be flexible based on what the user wants to do with the content.  That's the idea behind my application: blurring the line between essays and conversations, promoting dynamic collaboration spaces as well as individual content "ownership".</p>
<p>I want to see people doing things with their writing that move outside the rigid domain of "this is a blog", "this is a comment", etc.  That's not how ideas work in real life.  Is it possible to create a domain model that encourages not only blogs to cross-pollenate through ubiquitous dicusssions but also ensures that the surrounding discussions remain substantive and that new ideas grow as a result of the pollenation?  Do we have to draw lines and say, "that's your idea, this is mine"?  This is the idea behind ThreadSpinner - get people to use each others' content creatively while strengthening the personal investment in content creation.</p>
<p>As you see, this is bigger than a technical problem.  However, I think the development decisions will influence how viscous this sharing between people will be.  We'll see if my enthusiasm continues, but I think I'm off to a great start. If what I've written intrigues you, <a href="http://6thdensity.net/contact.html">drop me a line</a>.  I'd love to bounce ideas off developers.  I also have a subversion repository set up in case anybody wants to collaborate.
</p>
