--- 
wordpress_id: 562
title: Conspiracy as History
wordpress_url: http://blog.6thdensity.net/?p=562
layout: post
---
Over at a wonderful magazine called The Republic, Kevin Potvin <a href="http://republic-news.org/archive/141-repub/141_kevin_potvin_conspiracy.htm">argues</a> that conspiracy theorists are nothing more than present day historians recreating the probable power structures from available evidence.  No, they can't prove everything, and they can't always reconcile all the facts and make them fit hand in glove.  But a historian doesn't dismiss facts simply because they don't fit into the history he wants to tell.
<blockquote>A good historian looking at a distant time and place knows that everything he has as evidence before him has meaning and everything is somehow connected—or will be once he has finished writing his history. A 12th century scrap of paper with a partial list of sexually degrading acts found in the manuals of priests learning how to take confessions is at first so discordant, we can't begin to fathom how it came to be. Do we therefore throw it away, assume it has no meaning for us? Of course not. The piece of paper means something very important and it completely alters how we understand late-pagan culture in Europe and the frame of mind of the vanguard of the Church confronting it.

So when we get hold of executive compensation contracts from the heyday of the Enron era, and find CEOs holding out for things like a new dishwasher on a contract already worth several hundreds of millions of dollars, and find that also to be confusingly discordant, do we throw that information away because it doesn't make sense? No, we use that evidence to totally recreate what we think about corporate executive officers operating at the vanguard of our advanced capitalist economy, and to understand the demeaning service-sector society surrounding them, the very one we ourselves populate.

No doubt the Church would be terribly unhappy with what we would have had to say about their priests if we found those confessional manuals back when they were in circulation, and they would have argued articulately and vehemently against any less-than-flattering conclusions we might have drawn up because of them. So too do sycophants in the media today argue strongly against any unflattering conclusions we might draw about the executives in charge of our largest enterprises, based on what we learn about a few of them and their odd, even twisted, personal proclivities. But those denials, then as well as now, mean little against the hard evidence. Who owns the media in which those denials are made after all? Just as in the days of the Church, it is the same people being unflatteringly portrayed who have control over where and when, if ever, such portrayals will see the light of day. Of course their media will tell us to look away and ignore the evidence. That's what they bought the media to do.

<strong> Almost all that is dismissed as conspiracy theory today is really only good or poor attempts at writing history in our own time.</strong> But why is it that when we are talking of the histories of whole different places in whole different times, we easily accept that this or that group of powerful people made this or that important event happen, yet when it comes to histories of our own time and place, we automatically reject any suggestion of any group of people making any important event happen? Throughout history, every important event always has some group of people behind it, and these events always offer revealing meanings about the kind of societies in which they occur. It is the same today.</blockquote>
Don't make me cut and paste the entire article, <a href="http://republic-news.org/archive/141-repub/141_kevin_potvin_conspiracy.htm">read it yourself</a>.  It is spot on about the importance not just of an ongoing revisionist history, but applying those insights to a revisionist understanding of power structures in general.
