--- 
wordpress_id: 534
title: Left liberals at a crossroads
wordpress_url: http://blog.6thdensity.net/?p=534
layout: post
---
<p align="left"><a href="http://anthonygregory.com">Anthony Gregory</a> on the growing divide between the left liberal establishement and their base, <a href="http://www.lewrockwell.com/gregory/gregory94.html">as exemplified by Jon Stewart</a> (via LewRockwell.com):
<blockquote>The battle over the soul of American left-liberalism has begun. Neither                side is libertarian, of course. But one is clearly better from a                libertarian perspective. One offers a potential return to normalcy                – to take the steroids away from the "steroidal Democrats"                in the Republican Party – to retract, at least somewhat, the U.S.                empire to more tolerable and less globally dangerous levels; to                demilitarize the American police at home; even to keep cleaner accounts                for America’s financial house and temper the tyrannical extraction                of wealth from the taxpaying class for gorging by the corporate                state. Yes, it is not totally libertarian. But on the other side,                also fighting for the soul of left-liberalism, is the worst of all                worlds in American politics: sanguine for war and the nightstick,                and intent on inflating taxes on the rich so as to stabilize and                better manage the total state and empire. In other words, just as                Bush has been a "steroidal Democrat," Schumer offers a                glimpse into <a href="http://www.lewrockwell.com/gregory/gregory69.html">a                future Democratic administration of steroidal Republicans</a>. Let                the battle commence, and let us hope that <a href="http://www.lewrockwell.com/gregory/gregory53.html">if                the popular left ever rises again</a> in this country, it is more                inclined toward the sensibilities of Jon Stewart than the jackbooted                thuggery of Chuck Schumer.</blockquote>
As I've been trying to tell people, opposing this administration's foreign policy is about more than getting Republicans out of office: it's about giving the electorate a real anti-war party.  Let's remember that the Democratic establishment has a lot of Republican elements of which to rid themselves.  If left liberal independents can figure out that the powers they give their politicians will eventually be used by the others' politicians, maybe they'll start to see why leftism need not support the state (at least, reflexively).
