--- 
wordpress_id: 696
title: Carson on Labor and Libertarianism
wordpress_url: http://blog.6thdensity.net/?p=696
layout: post
---
<p><a href="http://mutualist.org">Kevin Carson</a> wrote <a href="http://mutualist.blogspot.com/2007/04/media-print-projection-embossed-body.html">a groundbreaking investigation of labor relations and vulgar libertarian double standards</a> that says everything I wanted to say on the matter, mostly.  What little is left is the subject of an upcoming article I'm writing on the subsidies for centralization that the State guarantee of security provides, but Carson goes a long way towards making my point for me. With in-depth analysis of historical issues in labor and government, he argues that <a href="http://en.wikipedia.org/wiki/Wagner_Act">Wagner</a> and <a href="http://en.wikipedia.org/wiki/Taft-Hartley_Act">Taft-Hartley</a> served more of capital's needs than labor's and that the answer is direct action by minority, wildcat organizing:
<blockquote><p>Whatever value the Wagner regime had for us in the past, it has outlived. We are getting kicked in the teeth under the old rules. If labor is to fight a successful counteroffensive, it has to stop playing by the bosses' rules. We need to fight completely outside the structure of Wagner and the NLRB's system of certification and contracts, or at least treat them as a secondary tactic in a strategy based on direct action.</p><p>In the neoliberal age, they've apparently decided that we need the contracts more than they do, and that "at-will" is the best thing for them. But I think if we took off the gloves, they might be the ones begging for a new Wagner act and contracts, all over again.</p><p>... We'll gladly forego legal protections against punitive firing of union organizers, and federal certification of unions, if you'll forego the court injunctions and cooling-off periods and arbitration. We'll leave you free to fire organizers at will, to bring back the yellow dog contract, if you leave us free to engage in sympathy and boycott strikes all the way up and down the production chain, boycott retailers, and strike against the hauling of scab cargo, etc., effectively turning every strike into a general strike. We give up Wagner (such as it is), and you give up Taft-Hartley and the Railway Labor Relations Act. And then we'll mop the floor with your ass.</p></blockquote>
It's a long but extremely worthwhile essay in its entirety, and comes with my highest recommendation.</p><p>Of course, it's up to me to ask the question that's on everybody's mind: WHO IS FISTICUFFS?  To shed some light on that topic, I'll post some of his other work:
<div align="center"><object width="425" height="350"><param name="movie" value="http://www.youtube.com/v/la7YnCKzaiA"></param><param name="wmode" value="transparent"></param><embed src="http://www.youtube.com/v/la7YnCKzaiA" type="application/x-shockwave-flash" wmode="transparent" width="425" height="350"></embed></object></div></p>
