--- 
wordpress_id: 647
title: Libertarian Solidarity with the Worker
wordpress_url: http://blog.6thdensity.net/?p=647
layout: post
---
I was very pleased to read Robert Russo's excellent article at <a href="http://richmondliberty.org">RichmondLiberty.org</a>, <a href="http://www.richmondliberty.org/mt/2007/03/freedom_in_the_workplace.php">Freedom in the Workplace</a>.  It's nice to know that another Richmonder sees libertarianism as the realization of the true proletariat revolution, as <a href="http://praxeology.net/blog/">Roderick Long</a> <a href="http://www.mises.org/story/2099">says</a>.  Russo expresses a crucial left libertarian insight when he takes on the authority of privileged, favored corporate interests.  The state allows them to give workers an unfair deal:
<blockquote>We are the only party, if any, that disagrees with the basic structure of the working world beyond fruitless personal complaints reserved for the home. We know the end result will be a company-state. We know the benefits of having just one corner in this market: authority relinquishing, accountability toward people instead of profit. I'll never forget applying to a foundation known for turning down people with Masters degrees for summer internships, saying I was used to small private foundations and the reply "we <strong>are</strong> a private foundation".  Big business is not a private enterprise, it is an institution riding on the <strong>coattails</strong> of privacy and abusing rights that belong to individuals. It is an opponent to all personal sentiments. The price we pay is time, a majority of our lives spent in a controlled environment where we are not citizens.

It is not government alone but all authority we must combat, and thankfully sometimes we are enabled. This could mean refusing to rat on a colleague, tweaking a client's eligibility for insurance, or contacting a qualified applicant who was rejected. Perhaps one day we will have a workers union. <a href="http://www.timesdispatch.com/servlet/Satellite?pagename=RTD/HTMLPage/RTD_HTMLPage&c=HTMLPage&cid=1031784382107">This link</a> is an excellent window into how Richmond truly operates and who pulls the strings.</blockquote>
This is about empowering people, not just disempowering the government.  It's about saying that individuals deserve the opportunity for life, liberty, and the pursuit of happiness. That right trumps the interests of abstract entities, insurgents of minority opinion who want to impose their special interest will,  and most of all, institutional corporate behavior.  I'm particularly happy to see mainstream libertarian support for the concept of real unions that pursue authentic worker interests (though most unions work hand in glove with the corporate bureaucratic establishment, unions like the <a href="http://iww.org">IWW</a> maintain the right of individuals to strike and bargain on their own terms).

Many thanks to Russo for an argument well made!
