--- 
wordpress_id: 685
title: Parcelling truth into cartesian space
wordpress_url: http://blog.6thdensity.net/?p=685
layout: post
---
In the near past I discovered what came to be a favorite source of left-leaning commentary and analysis,<a href="http://republic-news.org/"> The Republic of East Vancouver</a>, a small community paper published by one Kevin Potvin (you may remember him as the author of <a href="http://republic-news.org/archive/141-repub/141_kevin_potvin_conspiracy.htm">In Defence of Conspiracy Theories</a>).  Potvin had been running as a Green Party candidate for the Canadian legislature until <a href="http://www.google.com/search?hl=en&ie=UTF8&ned=us&q=%22A+revolting+confession%22">a media controversy</a> arose around an article he wrote about his reactions to 9/11 entitled "<a href="http://republic-news.org/archive/52-repub/repub_52_potvin_conf.html">A Revolting Confession</a>". I became aware of the original article because of a recent reflection Potvin compiled in his attempt to understand the whole ordeal.

His version of the story sounds exactly like what I'd expect from the mainstream media. Any time somebody speaks a truth that doesn't immediately conform to the preordained taxonomy of political positions, the media simply lies and distorts their position.  It's not so much that they want to be mean, I think; rather, if they allow people to transcend the ideological taxonomy through which they excel at projecting the news, they risk their position in society as news experts. Competition in <em><a href="http://en.wikipedia.org/wiki/World_view">weltanschauungen</a></em> is not appreciated.

The establishment thrives on inculcating a particular, uniform world view in the public. Even mainstream dichotomies (such as liberalism vs. conservatism) rest upon and take place within a common historical and ideological mythology.  Treading outside the matrix in public carries not only the danger of being ignored, but also the risk of being refashioned into whatever role the media narrative requires. The stakes are just too high for the establishment.
The offending passages of his original article even rubbed me the wrong way, initially:
<blockquote>I have a terrible confession to make. When I saw the first                     tower cascade down into that enormous plume of dust and paper,                     there was a little voice inside me that said, "Yeah!"                     When the second tower came down the same way, that little                     voice said, "Beautiful!" When the visage of the                     Pentagon appeared on the TV with a gaping and smoking hole                     in its side, that little voice had nearly taken me over, and                     I felt an urge to pump my fist in the air.

This is a revolting confession, I know. But it's what happened.</blockquote>
<!--more-->The more I read this passage, though, I realized how much courage it took for him to step forward, into the spotlight, and speak from his heart.  And, indeed, this is not an inhuman monster that wrote those words (he does, after all, describe his opinion as "revolting"). This is a person who is publicly and honestly trying to come to grips with what 9/11 means.  The only difference between him and your typical American is that he's not accepting 9/11 as some sort of unthinkable, exceptional event (which, from a humanitarian perspective, it certainly is not); instead, he's looking at it in the context of history and similar tragedies.
<blockquote>I know lots of people were killed. But then again, I see                     lots of people getting killed whenever I turn the TV news                     on, and frankly, it doesn't really get me anymore. Plenty                     more people are killed without my knowledge. A million Rwandans                     were killed in the space of 100 days a few years ago. That's                     a rate of six whole World Trade Center tower catastrophes                     every day for over three straight months running--and the                     whole thing barely registered on my radar.

Let's face facts. If the news on the morning of September                     11 was that 3,000 Tanzanians or Burmese had been killed, they                     wouldn't have broken in on regularly scheduled programming,                     or cancelled football games, and there'd be no conversation                     about it the next day. No one would say the world changed.                     It's been a long time since lots of people getting killed                     is, in itself, news, and we all know this, and we all live                     comfortably with it.</blockquote>
It's too easy to dismiss his article as support for Al Qaeda. What he writes about the scale of the tragedy - compared to other tragedies - carries the cold ring of truth. But even more importantly, he is being honest about the event and the emotional reactions that the mainstream media has supposedly poured over in such reflective detail. Personal and abject honesty in public is always something people find particularly uncomfortable: it's frightening to see somebody willingly submit to such a vulnerable and exposed position.

If his article makes us uncomfortable, then that's a good thing - we should probably be even less comfortable, given all the violence going on around the world. In fact, we should be so uncomfortable that, for one thing, we question the way news, information, and opinion are presented to us.  But to question dishonesty in the media would force us to confront our own complicity, our own dishonesty with ourselves.

Which is precisely why the media tore Potvin a new one. Nobody abandons the establishment's predesignated opinions and gets away with it. Otherwise, people might stop buying their opinions from the approved dealers and start coming up with their own.  They might even be forced to take responsibility for themselves and their minds.  That would quickly spiral out of control, because the establishment conserves its power only because most people think most other people believe in the established political taxonomy.  If that peer pressure is compromised, and people start seeing that it's O.K. to think for yourself, then where does that leave those elite in the media who have made their careers as the experts on the full range of proper opinions?  They no longer have anything of value to sell.

So the mainstream media uses its superior command of eyes and ears to denounce Potvin.  This is a tremendous pressure against which to stand.  But it's clear that an article like Potvin's is perceived as a real threat, and that at least is comforting.  Just like there is some small comfort, however wretched and tragic, in viewing 9/11 as proof that the world's greatest power can't get away with everything.

In <a href="http://republic-news.org/archive/161-repub/161_response.htm">the follow-up article</a>, he talks about his efforts to capture people's immediate reactions to the attacks.  I know that on September 12, 2001 I sent a short essay to my college newspaper urging people to look at the event in context and to refrain from overreaction.  I wish now that I could find that essay and share it with Potvin.  Those of us who don't respect the lines of the media's cartesian matrix need to stand by one another if we are ever to demonstrate what an alternative model of journalistic space looks like.
