--- 
wordpress_id: 642
title: RadRails vs. TextMate
wordpress_url: http://blog.6thdensity.net/?p=642
layout: post
---
I'm a big fan of <a href="http://radrails.org">RadRails</a> for doing <a href="http://rubyonrails.org">Rails</a> development.  This is probably because I started out on my first Rails project using <a href="http://rubyeclipse.sourceforge.net/">RDT</a> in <a href="http://www.eclipse.org/">Eclipse</a>, and coming from using Eclipse for Java development it already made sense.  I like the idea of everything being one place: browser, testing, rake, generators, EVERYTHING.  It's the way I'd like to do development ideally.

Most Rails developers are wedded to <a href="http://macromates.com/">TextMate</a> (the fact that it's Mac only and therefore automatically hip has nothing whatsoever to do with it).  TextMate is a great text editor.  It can do some cool <a href="http://subversion.tigris.org/">Subversion</a> stuff (though it pales in comparison to <a href="http://subclipse.tigris.org/">Subclipse</a>).  I'm using it for <a href="http://cvreg.org/projects/bookmarker">Bookmarker</a> because it's a great way to write code if that's ALL you want to do with it.  And a lot of Rails devvers have no problem going to the terminal or browser when needed, and that's fine for them.

But I'm very attracted to the idea of an open source IDE.  TextMate is not that, and RadRails is very close to being there (it's got a lot of issues, such as flakiness with the <a href="http://rake.rubyforge.org/">Rake</a> integration, not to mention the problems vanilla Eclipse has always had).  Unfortunately, <a href="http://radrails.org/blog/2007/3/5/radrails-future_1173078407">the RadRails guys aren't going to be able to do a lot of work on it anymore</a>.  I'm going to put my name out there as a willing helper but I don't know if I'll be able to learn Eclipse dev quickly enough, or if I'll even be able to commit to participating at all.  I've got so many other projects to work on, but RadRails is important to me.  So we'll see.

The cool thing about Rails is that the need for an IDE, compared to other languages, is compartively minor.  Yet I still like IDEs.  I know there are other Rails IDEs out there, but if I'm going to leave RadRails, I'm probably going to convert to the Rails standard: TextMate.  I think the whole reason I blogged this was to justify the fact that, even though I tried TextMate for 30 days for free and still prefer RadRails, I ended up buying it anyway.  Oh well.

And of course, this whole post is a bit outdated even as I write it: RadRails has <a href="http://radrails.org/blog/2007/3/8/radrails-aptana">announced a deal</a> with <a href="http://www.aptana.com/">Aptana</a>.  So Aptana is taking over RadRails development and eventually integrating it into their Eclipse-based IDE.  It will be interesting to see how this all plays out - especially since Aptana seems to have some cool javascript debugging features.  In the meantime, I have a new text editor and still intend to use (and possibly help develop) RadRails.
