--- 
wordpress_id: 773
title: Punishment as Extortion in Virginia
wordpress_url: http://blog.6thdensity.net/?p=773
layout: post
---
<p>I haven't met anybody who isn't outraged by Virginia's new "remedial fees" for traffic violations.  If you're from some other less God forsaken state, <a href="http://www.thenewspaper.com/news/18/1818.asp">here's a taste</a>:<blockquote><p>Driving as little as 15 MPH over the limit on an interstate highway now brings six license demerit points, a fine of up to $2500, up to one year in jail, and a new mandatory $1050 tax. The law also imposes an additional annual fee of up to $100 if a prior conviction leaves the motorist with a balance of eight demerit points, plus $75 for each additional point (up to $700 a year). The conviction in this example remains on the record for five years.</p><p>Other six-point convictions include "failing to give a proper signal," "passing a school bus" or "driving with an obstructed view." The same $1050 assessment applies, but the conviction remains on the record for eleven years.</p></blockquote>However, I'm now aware of somebody who's at least open to the idea: <a href="http://krehbiel.blogspot.com/2007/07/lingamfelter-op-ed-on-driver-fees.html">Thomas Krehbiel</a>.<blockquote><p>I don't fully understand why there's an uproar over these fees. I mean, I don't know about anyone else, but there's a lot of roads where I live that are in serious need of repairs.</p></blockquote>  He refers to <a href="http://manassasjm.com/servlet/Satellite?pagename=MJM%2FMGArticle%2FWPN_BasicArticle&c=MGArticle&cid=1173351980339&path=!opinion">a state legislator's clarification</a> of the bill:<blockquote><p>In plain English that means to be assessed the "abuser fee" for reckless speeding, the offender not only must be convicted of doing 20 mph over the 55 speed limit, but also must be driving without a valid operator's license due to a suspension or revocation for a prior moving violation, plus (and this is a key point) the reckless speeding he is charged with must be the sole and proximate result of the death of another person. In other words, you're not speaking here of a driver simply going too fast, but one who is also driving on a suspended license and killed someone in the process. <strong>My bet is most folks agree that this kind of driver should be assessed heavily, even those General Assembly members who voted against the Compromise Transportation package in 2007, but supported a stand-alone abuser fee bill in the 2006 Special Session.</strong></p></blockquote>Now, I'm not sure if I trust the opinion of a legislator over that of the state Supreme Court, which <a href="http://www.thenewspaper.com/rlc/docs/2007/va-drivertax.pdf">made no such distinction</a>.</p>
<p>Even if the legislator is correct, though, this bill is unjust. It confuses a penalty, which is designed to punish in proportion to the crime, with a tax, which is designed to spread the costs of government among citizens.  When the general costs of government go up, as is the case with traffic maintenance costs in Virginia, revenue must be raised.  But that's hard when you're a Virginia Republican who's vowed not to raise taxes.  So find a small minority of citizens who, ahem, <em>deserve</em> it, and you can make them shoulder the burden.</p>
<p>So when the legislator says, "My bet is most folks agree that this kind of driver should be assessed heavily", he may be correct.  But I believe most folks would wish for <em>any</em> offender to be assessed a penalty that a <em>judge</em> finds appropriate, according to the circumstances of the situation.  For a legislator to levy a sweeping tax on a class of offenders is essentially another mandatory minimum, driven not only by crime hysteria but also <em>budget</em> hysteria.  Why should people respect the state's law when it has morphed from even a poor attempt at justice into sheer discrimination and extortion?</p><p>Answer: they shouldn't - they should demand a <a href="http://en.wikipedia.org/wiki/Polycentric_law">separation of law and state</a> so that politicians can't distort justice to hide their own incompetence.</p>
