--- 
wordpress_id: 1397
title: Quote of the Day
wordpress_url: http://blog.6thdensity.net/?p=1397
layout: post
---
<p>Wearing my <a href="http://www.dieselsweeties.com/blog/?p=347">Obama skeptic shirt</a> to the <a href="http://www.facebook.com/event.php?eid=44785577842&ref=nf">BioDiesel show</a> last night spawned one disappointing conversation.  I kept trying to explain my postion: Obama's not radical or leftist <em>enough</em>, he's perpetuating a failed economic system through these bailouts and investment projects, we need to reconsider the premises or our system rather than patch it up.  Eventually I had to clarify my anarchist principles, and I wish I could have read this Proudhon passage verbatim to the guy:</p>
<blockquote>To be GOVERNED is to be watched, inspected, spied upon, directed, law-driven, numbered, regulated, enrolled, indoctrinated, preached at, controlled, checked, estimated, valued, censured, commanded, by creatures who have neither the right nor the wisdom nor the virtue to do so. To be GOVERNED is to be at every operation, at every transaction noted, registered, counted, taxed, stamped, measured, numbered, assessed, licensed, authorized, admonished, prevented, forbidden, reformed, corrected, punished. It is, under pretext of public utility, and in the name of the general interest, to be place[d] under contribution, drilled, fleeced, exploited, monopolized, extorted from, squeezed, hoaxed, robbed; then, at the slightest resistance, the first word of complaint, to be repressed, fined, vilified, harassed, hunted down, abused, clubbed, disarmed, bound, choked, imprisoned, judged, condemned, shot, deported, sacrificed, sold, betrayed; and to crown all, mocked, ridiculed, derided, outraged, dishonored. That is government; that is its justice; that is its morality.</blockquote>
<p align=right><a href="http://en.wikipedia.org/wiki/Pierre-Joseph_Proudhon">P. J. Proudhon</a>, General Idea of the Revolution in the Nineteenth Century, translated by John Beverly Robinson (London: Freedom Press, 1923), pp. 293-294.<p><p>I'm not against Obama per se. I simply don't want to be governed.</p>
